name: scTAB_new
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - alsa-lib=1.2.14
  - anndata=0.7.8
  - astor=0.8.1
  - asttokens=3.0.0
  - astunparse=1.6.3
  - attr=2.5.2
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.29
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.19
  - aws-c-mqtt=0.10.7
  - aws-c-s3=0.6.7
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - backcall=0.2.0
  - blosc=1.21.6
  - bokeh=3.1.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.14.3
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cffi=1.17.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.1.1
  - cuda-version=11.1
  - cudatoolkit=11.1.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.3
  - dask-core=2023.5.0
  - dbus=1.16.2
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.14.1
  - gast=0.4.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - glib=2.86.0
  - glib-tools=2.86.0
  - glog=0.7.1
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio-tools=1.62.2
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.1.0
  - h5py=2.10.0
  - harfbuzz=11.5.0
  - hdf5=1.10.6
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keras-preprocessing=1.1.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - legacy-api-wrap=1.4
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=20.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdeflate=1.23
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgpg-error=1.55
  - libgrpc=1.62.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm19=19.1.7
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.25
  - libopus=1.5.2
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libthrift=0.20.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuuid=2.41.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=1.6.2
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.5
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.7
  - mpg123=1.32.9
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - natsort=8.4.0
  - nccl=2.27.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nomkl=1.0
  - nspr=4.37
  - nss=3.116
  - numexpr=2.8.4
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - orc=2.0.2
  - parso=0.8.4
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pixman=0.46.4
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-xgboost=1.6.2
  - pyarrow-core=17.0.0
  - pycparser=2.22
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyparsing=3.1.4
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytables=3.8.0
  - python=3.8.20
  - python-flatbuffers=24.3.25
  - python-rapidjson=1.20
  - python-tzdata=2024.2
  - python_abi=3.8
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - re2=2023.09.01
  - readline=8.2
  - s2n=1.5.5
  - safetensors=0.4.4
  - scanpy=1.8.2
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=61.0.0
  - sinfo=0.3.1
  - sip=6.7.12
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - sqlite=3.50.4
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - stdlib-list=0.11.0
  - tbb=2022.2.0
  - tblib=3.0.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - termcolor=2.4.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - tritonclient=2.49.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - umap-learn=0.5.6
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - werkzeug=3.0.6
  - wheel=0.45.1
  - wrapt=1.16.0
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgboost=1.6.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.4.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==1.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - betterproto==1.2.5
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.2.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - dask==2023.3.2
      - dask-cuda==23.4.0
      - distributed==2023.3.2.1
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.70.0
      - grpclib==0.4.8
      - hpack==4.0.0
      - isodate==0.7.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lightning==2.3.3
      - lightning-utilities==0.11.9
      - llvmlite==0.41.1
      - markdown==3.7
      - matplotlib==3.4.3
      - merlin-core==23.8.0
      - merlin-dataloader==23.8.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.1.0
      - npy-append-array==0.9.19
      - numba==0.58.1
      - numpy <= 1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - packaging==24.2
      - pandas==1.5.3
      - pip==25.0.1
      - propcache==0.2.0
      - protobuf==3.20.3
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pynvml==11.4.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2025.2
      - rdflib==7.2.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.2.2
      - six==1.17.0
      - sparqlwrapper==2.0.0
      - stringcase==1.2.0
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorflow-metadata==1.14.0
      - torch==2.4.1
      - torchmetrics==1.5.2
      - triton==3.0.0
      - yarl==1.15.2
prefix: /projects/b1042/GoyalLab/jaekj/python/scTAB
